### PR TITLE
add python 3 and clean code

### PR DESCRIPTION
**Pull request by wannaphongcom**
fix https://github.com/hermanschaaf/pythai/issues/3

### CODE REVIEW

**Comment by hermanschaaf** [comment]
Hey @wannaphongcom, this is great! As you probably noticed, I haven't touched this library in years.

Browsing quickly through the changes, I have two questions: 

 1. why is the python 3 code block in `libthai.c`, so much longer than the python 2 block?
 2. why was the test case on line 28 (`TestSentence(u"hello there ด้ต้อ", u"hello there ด้ ต้อ", 4)`) removed?

**Comment by wannaphongcom** [comment]
1.  I write code  python 2/3 compatibility.
Python 3 https://github.com/hermanschaaf/pythai/pull/4/files#diff-3db929d0ced3dbc00b22f8ece80b3884R4
Python 2 https://github.com/hermanschaaf/pythai/pull/4/files#diff-3db929d0ced3dbc00b22f8ece80b3884R85
2. 
```
test_contains_thai (pythai.tests.PyThaiCase) ... ok
test_split (pythai.tests.PyThaiCase) ... ERROR
test_word_count (pythai.tests.PyThaiCase) ... ERROR

======================================================================
ERROR: test_split (pythai.tests.PyThaiCase)
hello ที่ ได้ ต้อ somehidden hello ที่ ได้ ต้อ somehidden
hello there ด้ ต้อ hello there ด้ต้อ
FAIL
test_word_count (pythai.tests.PyThaiCase) ... FAIL

======================================================================
FAIL: test_split (pythai.tests.PyThaiCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/c/pythai/pythai/tests.py", line 45, in test_split
    self.assertEqual(' '.join(pythai.split(sentence.sentence)), sentence.split)
AssertionError: 'hello there ด้ต้อ' != 'hello there ด้ ต้อ'
- hello there ด้ต้อ
+ hello there ด้ ต้อ
?               +


======================================================================
FAIL: test_word_count (pythai.tests.PyThaiCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/c/pythai/pythai/tests.py", line 39, in test_word_count
    self.assertEqual(pythai.word_count(sentence.sentence), sentence.word_count)
AssertionError: 3 != 4

----------------------------------------------------------------------
Ran 3 tests in 0.011s

FAILED (failures=2)
```

**Comment by wannaphongcom** [comment]
in python 2.7
```
การ ที่ ได้ ต้อง แสดง ว่า งาน ดี การ ที่ ได้ ต้อง แสดง ว่า งาน ดี
บริษัท ชื่อ XY&Z - คุย กับ xyz@demo.com บริษัท ชื่อ XY&Z - คุย กับ xyz@demo.com
ประโยค ว่า The quick brown fox jumped over the lazy dogs ประโยค ว่า The quick brown fox jumped over the lazy dogs
การ การ
hello ที่ ได้ ต้อ somehidden hello ที่ ได้ ต้อ somehidden
hello there ด้ ต้อ hello there ด้ต้อ
FAIL
test_word_count (pythai.tests.PyThaiCase) ... FAIL

======================================================================
FAIL: test_split (pythai.tests.PyThaiCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/c/pythai/pythai/tests.py", line 45, in test_split
    self.assertEqual(' '.join(pythai.split(sentence.sentence)), sentence.split)
AssertionError: u'hello there \u0e14\u0e49\u0e15\u0e49\u0e2d' != u'hello there \u0e14\u0e49 \u0e15\u0e49\u0e2d'
- hello there \u0e14\u0e49\u0e15\u0e49\u0e2d
+ hello there \u0e14\u0e49 \u0e15\u0e49\u0e2d
?               +


======================================================================
FAIL: test_word_count (pythai.tests.PyThaiCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/c/pythai/pythai/tests.py", line 39, in test_word_count
    self.assertEqual(pythai.word_count(sentence.sentence), sentence.word_count)
AssertionError: 3 != 4

----------------------------------------------------------------------
Ran 3 tests in 0.018s

FAILED (failures=2)
```

**Comment by wannaphongcom** [comment]
The test kit has a problem.

**Pull request merged**
